name: Normalize line endings to LF

on:
  workflow_dispatch: {}  # run manually from Actions tab

permissions:
  contents: write   # <-- crucial

jobs:
  normalize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true   # use GITHUB_TOKEN for push
          fetch-depth: 0              # get full history so renormalize is safe
      - name: Enforce LF via .gitattributes & renormalize
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config core.autocrlf false
          git add --renormalize .
          if ! git diff --cached --quiet; then
            git commit -m "Normalize line endings to LF"
            git push
          else
            echo "No changes to normalize."
          fi
